---
# template source: https://github.com/bretfisher/super-linter-workflow/blob/main/templates/call-super-linter.yaml
name: Lint Code Base

on:
  
  push:
    branches: [master]
  
  pull_request:

jobs:
  call-super-linter:

    name: Call Super-Linter
    
    permissions:
      contents: read # clone the repo to lint
      statuses: write #read/write to repo custom statuses

  
    uses: a9596/super-linter-workflow/.github/workflows/reusable-super-linter.yaml@main
    
    ### Optional settings examples
    
    # with:
      ### For a DevOps-focused repository. Prevents some code-language linters from running
      ### defaults to false
      # devops-only: false
      
      ### A regex to exclude files from linting
      ### defaults to empty
      # filter-regex-exclude: html/.*